site_name: honlSoft Developer Documentation
repo_url: https://gitlab.com/jerhon/developer-notes
site_url: https://jerhon.gitlab.io/developer-notes
site_author: Jeremy Honl
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true